### ISSUE TITLE
Code is failing with SyntaxError

### ISSUE THREAD

**Issue by PrudhviKrish** [Infinidat/infi.win32service#1]
Hi,

I have observed following error message while using this package.
>   from .service import SERVICE_STATUS, SERVICE_NOTIFY, ServiceState, ServiceControlsAccepted, Service
E     File "C:\Python34\lib\site-packages\infi\win32service\service.py", line 230
E       except WindowsError, e:
E                          ^
E   SyntaxError: invalid syntax

Python3.X will not support this syntax. Can you please provide support for this?

Thanks,
Prudhvi

**Comment by wiggin15** [comment]
Thank you for reporting this. infi.win32service currently doesn't support Python 3.x. We plan to fix this but this is not a priority right now so there is no timeline for when this will be fixed.

**Comment by wiggin15** [comment]
Hello @PrudhviKrish . Just wanted to let you know that initial support for Python 3 has been added to the code. This is not thoroughly tested yet (though the tests do pass) but you can start using the code from the repository if you want. If you run into any other issues, feel free to report them. Thanks.
